name: app_using_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cached: ^1.7.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.12.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_storage: 11.6.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.0.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.0.8
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/data/data.json
  uses-material-design: true
